language: objective-c
cache:
    directories:
    - $HOME/.ccache
install:
- gem install xcpretty
- brew install ccache
- PATH=$PATH:/usr/local/opt/ccache/libexec
- export PYTHONUSERBASE=~/.local
- easy_install --user scan-build
script:
- set -o pipefail && xcodebuild -project "CrashGuard.xcodeproj" -scheme "CrashGuard" build | xcpretty
- set -o pipefail && scan-build --status-bugs xcodebuild -project "CrashGuard.xcodeproj" -scheme "CrashGuard" clean analyze | xcpretty
- set -o pipefail && xcodebuild -project "CrashGuard.xcodeproj" -scheme "Test" build | xcpretty
- set -o pipefail && scan-build --status-bugs xcodebuild -project "CrashGuard.xcodeproj" -scheme "Test" clean analyze | xcpretty
before_script:
- ccache -s
- ccache -z
after_script:
- ccache -s
notifications:
    slack: xs-labs:FXh1yLXNkpcVxKZhZU6icdhI
